### ISSUE TITLE
Twitter account update for Chris Evans Labour/Co-operative MP for Islwyn 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/parlparse#110]
[From Twitter](https://twitter.com/huwmjames/status/1186963063683063808):
>Hey @ChrisEvansMP, are you aware that the Twitter link on @TheyWorkForYou points to a @JamesfWells page? 

At the time of writing:

https://www.theyworkforyou.com/mp/24721/chris_evans/islwyn/recent

links to

https://twitter.com/EvansForIslwyn

which currently has a bio stating:

>Support @JamesFWells, prospective parliamentary Candidate for Islwyn,

The @EvansForIslwyn account been mentioned by Labour accounts suggesting it was at one point a genuine account. 

https://twitter.com/WelshLabour/status/872980163033739264
https://twitter.com/BlackwoodLabour/status/863454026406539266

But it looks as if @ChrisEvansMP would be a better Twitter account for to link to anyway. 

One for @JenMysoc ?

**Comment by JenMysoc** [comment]
Unfortunately now I'm not sure how we get twitter accounts into TWFY so possible one for @dracos
