### ISSUE TITLE
List of current lords is out of date

### ISSUE THREAD

**Issue by andylolz** [mysociety/parlparse#112]
While it looks as though new lords have recently been added, I think some former lords need to be marked as such, by adding `end_date`s to [members/people.json](https://github.com/mysociety/parlparse/blob/master/members/people.json).

For instance, Lord Ashdown’s death in 2018 has not been recorded. As a result, he’s still shown as current on TheyWorkForYou:
https://www.theyworkforyou.com/peer/10015/lord_ashdown_of_norton-sub-hamdon

I haven’t looked closely, but I suspect there are ~100 similar examples.

**Comment by dracos** [comment]
Have updated the script to spot missing end dates as well as new lords, so hopefully this is fixed
