### ISSUE TITLE
We don't always know the difference between the Marquess and the Lord Bishop of Salisbury

### ISSUE THREAD

**Issue by abimysoc** [mysociety/parlparse#127]
Marquess: https://members.parliament.uk/member/1124/career

Lord Bishop: https://members.parliament.uk/member/4350/career

https://www.theyworkforyou.com/search/?pid=13261

Appears to me that everything up to 2001 is "Viscount Cranborne" (the Marquess of Salisbury) from historic Hansard, and then after a gap of some years we start listing post-2019 contributions as though they are the same member, but they're actually by the Lord Bishop of Salisbury. The Marquess retired from the Lords in 2017.

We do know about the Lord Bishop. He's https://www.theyworkforyou.com/peer/25265/bishop_of_salisbury and he has a load of Written Answers attributed to him correctly, just not the debates.

**Comment by dracos** [comment]
We switched from PimsId to MnisId in Hansard parsing in September 2020. The problem with PimsId (which was the only ID until more recently, and we didn't realise this issue anyway) was that it was not unique per person, but unique per location, so both the Marquess of Salisbury and any Bishops of Salisbury all had the same PimsId. They thankfully all have different MnisIds, so this should be okay nowadays.

This affects eleven speeches (as you say, written answers are okay, they always went off Mnis) in 2019/2020, all misattributed, on 2019-02-13, 2019-03-04, 2019-03-26, 2019-05-02, 2019-06-05, 2019-10-21, 2019-10-23, 2020-03-03, 2020-03-04, 2020-03-05, and 2020-07-13. Should be updated and fixed now.
