### ISSUE TITLE
Duplicate entry for Lord Carmichael/Neil Carmichael

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/parlparse#133]
The two following entries are the [same person](https://en.wikipedia.org/wiki/Neil_Carmichael,_Baron_Carmichael_of_Kelvingrove):

- https://www.theyworkforyou.com/peer/13265/lord_carmichael_of_kelvingrove
- https://www.theyworkforyou.com/mp/22046/neil_carmichael/glasgow_kelvingrove

**Comment by dracos** [comment]
Thanks, hopefully fixed in https://github.com/mysociety/parlparse/commit/409b8815cd4770350c616c97a83fa82cde9309b9
