### ISSUE TITLE
Needs update for recent changes in MPs

### ISSUE THREAD

**Issue by mashedkeyboard** [mysociety/parlparse#152]
James Brokenshire, Owen Paterson and Jack Dromey are all still listed as being in office, it seems. I've been trying to update this myself but have run into some trouble, as running crawl-members and update-members followed by json-add-new-parl-ids doesn't seem to be helping. Could someone with more experience take a look?

**Comment by dracos** [comment]
Looks like you'd got a lot of the way! Made some comments on the PR, and have included your commit with a few tweaks along with some uncommitted changes, thanks.
