### ISSUE TITLE
Lords no longer publishing HTML Hansard written answers/statements

### ISSUE THREAD

**Issue by dracos** [mysociety/parlparse#17]
(Going from http://www.parliament.uk/business/publications/hansard/lords/by-date/#session=26&year=2015&month=0&day=26 ) Will have to adapt new WA parser to fetch from http://www.parliament.uk/business/publications/written-questions-answers-statements/ where they are now based.

**Comment by lizconlan** [comment]
ugh, it appears that the new HTML and PDFs for this don't marry up with the Hansard column numbers

**Comment by dracos** [comment]
Lords Written Answers back as of a87cb3b8c97168e736f09b6438ba71b94a87ed33.

**Comment by dracos** [comment]
Lords Written Statements back as of ae4fed191b4aeaa13af6afa0562039d6465feb3a.
Will switch Commons to this system now,it has PDF links and so on, and improve the dupe spotting.
