### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by slowe** [mysociety/parlparse#177]
I noticed that there are some encoding issues with the new RMFI data at https://www.theyworkforyou.com/regmem/?f=2024-08-04. For instance MP `Siân Berry` is rendering as `SiÃ¢n Berry`. It is also affecting individual MP pages such as https://www.theyworkforyou.com/regmem/?p=25752 It looks like an ANSI/UTF8 issue.

In addition it looks as though there are encoding issues with `£` as a lot show up as `Â£`.

**Comment by dracos** [comment]
Thanks, this should now be fixed. The source XML switched from ISO-8859-1 to UTF-8 in 2023 and the code didn't realise.
