### ISSUE TITLE
Scotland:  some plenary sitting days are missing because the parser saves them to incorrect location

### ISSUE THREAD

**Issue by handelaar** [mysociety/parlparse#179]
These debates exist in TWFY
https://www.theyworkforyou.com/pwdata/scrapedxml/sp-new/meeting-of-the-parliament/

These do not
https://www.theyworkforyou.com/pwdata/scrapedxml/sp-new/meeting-of-the-parliament--/

**Comment by dracos** [comment]
Thanks for spotting that - it got confused working out the name when it had "Draft..." stuff in it. Hopefully moved them all across and imported them now.
