### ISSUE TITLE
Move names from memberships to persons

### ISSUE THREAD

**Issue by dracos** [mysociety/parlparse#25]
With date ranges if needed.

**Comment by tmtmtmtm** [comment]
Currently a name change requires a new Membership — after this is done, will there still be those multiple Memberships, or will those be consolidated into a single one, spanning a period where there were multiple names?

**Comment by dracos** [comment]
There's only one example in this dataset (we avoided any others because it was awkward). I don't know if anyone will have stored and be using those member IDs elsewhere, hopefully not, but for consistency yes, I think it'd be consolidated (and if anyone notices/complains, we can explain).

**Comment by tmtmtmtm** [comment]
I'm currently using them at http://data.everypolitician.org/northern_ireland/term_table.html but it's not automatically updating, so I can manually tweak anything required once they change.

**Comment by dracos** [comment]
This has been done (and the redirects of old memberships were doing with a 'redirect' entry, e.g. `{ "id": "uk.org.publicwhip/member/90491", "redirect": "uk.org.publicwhip/member/90425" }`, which we also use to merge people in person).
