### ISSUE TITLE
members/constituencies.xml missing

### ISSUE THREAD

**Issue by rbairwell** [mysociety/parlparse#29]
The members/constituencies.xml file is missing (it appears to have been replaced with a JSON file) which seems to be stopping PublicWhip updating. It's also listed as a file on http://parser.theyworkforyou.com/members.html .

**Comment by struan** [comment]
@rbairwell I'm in the process of updating the loader to fix this.

**Comment by struan** [comment]
I've updated the loader to use the new JSON format.
