### ISSUE TITLE
Ken Macintosh duplicate (person/14035 and person/25098)

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/parlparse#38]
I'm not sure whether there's a process for merging these, beyond simply deleting 25098 and adjusting membership 80477…

**Comment by dracos** [comment]
Thanks; there's a script (json-merge-people) that does most/all of a merge for you (had to tidy up the names after in this case). It doesn't delete an entry, it changes it to a 'redirect' entry so that IDs in XML files and URLs still function.
