### ISSUE TITLE
Natalie McGarry showing as SNP

### ISSUE THREAD

**Issue by rbairwell** [mysociety/parlparse#46]
In https://github.com/mysociety/parlparse/blob/master/members/people.json for id uk.org.publicwhip/person/25303 shows Natalie McGarry as having a current_party of "Scottish National Party" but http://data.parliament.uk/membersdataplatform/services/mnis/members/query/name*McGarry/ and http://www.parliament.uk/biographies/commons/natalie-mcgarry/4428 shows her as Independent (see also http://www.bbc.co.uk/news/uk-scotland-scotland-politics-34914067 ).

(affecting PublicWhip http://www.publicwhip.org.uk/mp.php?mpn=Natalie_McGarry&mpc=Glasgow_East&house=commons and http://www.theyworkforyou.com/mp/25303/natalie_mcgarry/glasgow_east )

**Comment by dracos** [comment]
Fixed in 63f65ba8bf33496a9b263957a57acc9dbace1b4e, thanks.
