### ISSUE TITLE
scripts/ynmp updates needed for the 2017 General Election

### ISSUE THREAD

**Issue by mhl** [mysociety/parlparse#83]
At a quick look, the following things need to be updated, at least:

* https://edit.yournextmp.com/media/candidates.csv should now be https://candidates.democracyclub.org.uk/media/candidates-all.csv (and make sure there's a condition to ignore elections other than `parl.2017-06-08`) or use the smaller: https://candidates.democracyclub.org.uk/media/candidates-parl.2017-06-08.csv
* Some of the columns have been renamed (e.g. `constituency`)
* There's no `mapit_id` column any more, but there is a `mapit_url`. (n.b. the post IDs are no longer MapIt Area IDs)
* The fixtures.csv file needs to be updated with those changes

I'll be trying out setting people as elected on the DC YNR staging site, so we could test again then after that as well.

**Comment by struan** [comment]
Fixed in 89012a4
