### ISSUE TITLE
MSPs missing: Tom Mason + Jamie Halcro Johnston

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/parlparse#90]
both appointed on June 20th:

* http://www.parliament.scot/msps/currentmsps/jamie-halcro-johnston-msp.aspx
* https://en.wikipedia.org/wiki/Jamie_Halcro_Johnston

* http://www.parliament.scot/msps/currentmsps/tom-mason-msp.aspx
* https://en.wikipedia.org/wiki/Tom_Mason_(Scottish_politician)

**Comment by chrismytton** [comment]
Also Michelle Ballantyne

- http://www.parliament.scot/msps/currentmsps/Michelle-Ballantyne.aspx
- https://en.wikipedia.org/wiki/Michelle_Ballantyne

**Comment by struan** [comment]
Fixed in commits leading up to d4e1ebb
